#!/usr/bin/env python3
"""Durable repository-local memory for Project Guardian Engineer."""
from __future__ import annotations

import argparse
import datetime as dt
import fnmatch
import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any, Iterable

AI_DIR = ".ai"
EVENTS = Path(AI_DIR) / "memory" / "events.jsonl"
INDEX = Path(AI_DIR) / "MEMORY_INDEX.md"
CRITICAL = Path(AI_DIR) / "CRITICAL_INVARIANTS.md"
PROTECTED = Path(AI_DIR) / "PROTECTED_AREAS.json"
CURRENT = Path(AI_DIR) / "CURRENT_STATE.md"
SESSION = Path(AI_DIR) / "session" / "current.json"
CRIT_START = "<!-- PROJECT-GUARDIAN:CRITICAL:START -->"
CRIT_END = "<!-- PROJECT-GUARDIAN:CRITICAL:END -->"


def now_iso() -> str:
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()


def git_root(start: str | Path | None = None) -> Path:
    cwd = Path(start or os.getcwd()).resolve()
    try:
        out = subprocess.check_output(
            ["git", "-C", str(cwd), "rev-parse", "--show-toplevel"],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
        if out:
            return Path(out).resolve()
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass
    return cwd


def ensure_files(root: Path) -> None:
    (root / EVENTS).parent.mkdir(parents=True, exist_ok=True)
    (root / SESSION).parent.mkdir(parents=True, exist_ok=True)
    if not (root / EVENTS).exists():
        (root / EVENTS).write_text("", encoding="utf-8")
    if not (root / INDEX).exists():
        (root / INDEX).write_text(
            "# Project Memory Index\n\nGenerated by Project Guardian. Do not use this as a substitute for evidence.\n",
            encoding="utf-8",
        )
    if not (root / CRITICAL).exists():
        (root / CRITICAL).write_text(
            "# Critical Project Invariants\n\n"
            "Keep only high-signal, proven rules here. User-written content outside the managed block is preserved.\n\n"
            f"{CRIT_START}\n_No critical records yet._\n{CRIT_END}\n",
            encoding="utf-8",
        )
    if not (root / CURRENT).exists():
        (root / CURRENT).write_text(
            "# Current Project State\n\n"
            "Keep this concise: active architecture, current branch/release status, and unresolved blockers only.\n",
            encoding="utf-8",
        )
    if not (root / PROTECTED).exists():
        write_json(root / PROTECTED, {"version": 1, "areas": []})


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    tmp.replace(path)


def read_json(path: Path, default: Any) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError):
        return default


def read_events(root: Path) -> list[dict[str, Any]]:
    path = root / EVENTS
    if not path.exists():
        return []
    records: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                value = json.loads(line)
            except json.JSONDecodeError:
                continue
            if isinstance(value, dict):
                records.append(value)
    return records


def normalize_list(items: Iterable[str] | None) -> list[str]:
    result: list[str] = []
    for raw in items or []:
        for part in raw.split(","):
            value = part.strip()
            if value and value not in result:
                result.append(value)
    return result


def record_fingerprint(record: dict[str, Any]) -> str:
    stable = {
        "kind": record.get("kind", ""),
        "title": record.get("title", ""),
        "summary": record.get("summary", ""),
        "files": sorted(record.get("files", [])),
        "guard": record.get("guard", ""),
    }
    raw = json.dumps(stable, sort_keys=True, ensure_ascii=True).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()[:16]


def current_session_id(root: Path) -> str | None:
    data = read_json(root / SESSION, {})
    value = data.get("session_id") if isinstance(data, dict) else None
    return str(value) if value else None


def append_record(root: Path, record: dict[str, Any]) -> tuple[bool, dict[str, Any]]:
    ensure_files(root)
    record["fingerprint"] = record_fingerprint(record)
    existing = read_events(root)
    for item in reversed(existing[-300:]):
        if item.get("fingerprint") == record["fingerprint"]:
            return False, item
    with (root / EVENTS).open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(record, ensure_ascii=False, sort_keys=True) + "\n")
    refresh_views(root)
    return True, record


def md_escape(text: str) -> str:
    return text.replace("\n", " ").replace("|", "\\|").strip()


def record_line(item: dict[str, Any]) -> str:
    flags = []
    if item.get("critical"):
        flags.append("CRITICAL")
    kind = str(item.get("kind", "memory")).upper()
    flags.append(kind)
    stamp = str(item.get("timestamp", ""))[:10]
    title = md_escape(str(item.get("title", "Untitled")))
    summary = md_escape(str(item.get("summary", "")))
    guard = md_escape(str(item.get("guard", "")))
    suffix = f" Guard: {guard}" if guard else ""
    return f"- **{' / '.join(flags)}** `{stamp}` - **{title}**: {summary}{suffix}"


def refresh_views(root: Path) -> None:
    ensure_files(root)
    records = read_events(root)
    critical = [r for r in records if r.get("critical")]
    recent = records[-40:]

    lines = [
        "# Project Memory Index",
        "",
        "Generated from `.ai/memory/events.jsonl`. Read critical items first, then search the event log for task-specific terms.",
        "",
        "## Critical",
        "",
    ]
    lines.extend(record_line(r) for r in critical[-25:])
    if not critical:
        lines.append("_No critical records yet._")
    lines += ["", "## Recent", ""]
    lines.extend(record_line(r) for r in recent)
    if not recent:
        lines.append("_No memory records yet._")
    (root / INDEX).write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    crit_lines = [CRIT_START]
    crit_lines.extend(record_line(r) for r in critical[-40:])
    if not critical:
        crit_lines.append("_No critical records yet._")
    crit_lines.append(CRIT_END)
    crit_block = "\n".join(crit_lines)
    path = root / CRITICAL
    original = path.read_text(encoding="utf-8") if path.exists() else "# Critical Project Invariants\n\n"
    if CRIT_START in original and CRIT_END in original:
        before, rest = original.split(CRIT_START, 1)
        _, after = rest.split(CRIT_END, 1)
        merged = before.rstrip() + "\n\n" + crit_block + after
    else:
        merged = original.rstrip() + "\n\n" + crit_block + "\n"
    path.write_text(merged.rstrip() + "\n", encoding="utf-8")


def cmd_init(args: argparse.Namespace) -> int:
    root = git_root(args.repo)
    ensure_files(root)
    refresh_views(root)
    print(f"Initialized guardian memory at {root / AI_DIR}")
    return 0


def cmd_add(args: argparse.Namespace) -> int:
    root = git_root(args.repo)
    ensure_files(root)
    record: dict[str, Any] = {
        "id": hashlib.sha1(f"{now_iso()}|{args.kind}|{args.title}".encode()).hexdigest()[:12],
        "timestamp": now_iso(),
        "kind": args.kind,
        "title": args.title.strip(),
        "summary": args.summary.strip(),
        "tags": normalize_list(args.tags),
        "files": normalize_list(args.files),
        "evidence": args.evidence.strip() if args.evidence else "",
        "guard": args.guard.strip() if args.guard else "",
        "validation": args.validation.strip() if args.validation else "",
        "critical": bool(args.critical),
        "session_id": current_session_id(root),
    }
    created, saved = append_record(root, record)
    if created:
        print(f"Saved memory {saved['id']}: {saved['title']}")
    else:
        print(f"Duplicate memory already exists: {saved.get('id', saved.get('fingerprint'))}")
    return 0


def score_record(item: dict[str, Any], terms: list[str]) -> int:
    text = " ".join(
        [
            str(item.get("title", "")),
            str(item.get("summary", "")),
            str(item.get("evidence", "")),
            str(item.get("guard", "")),
            " ".join(item.get("tags", []) or []),
            " ".join(item.get("files", []) or []),
        ]
    ).lower()
    score = 0
    for term in terms:
        if term in text:
            score += 2 if term in str(item.get("title", "")).lower() else 1
    if item.get("critical"):
        score += 1
    return score


def cmd_search(args: argparse.Namespace) -> int:
    root = git_root(args.repo)
    ensure_files(root)
    terms = [t.lower() for t in args.query.split() if len(t) > 1]
    ranked = []
    for item in read_events(root):
        score = score_record(item, terms)
        if score:
            ranked.append((score, str(item.get("timestamp", "")), item))
    ranked.sort(key=lambda x: (x[0], x[1]), reverse=True)
    for score, _, item in ranked[: args.limit]:
        print(json.dumps({"score": score, **item}, ensure_ascii=False, sort_keys=True))
    if not ranked:
        print("No matching memory records.")
    return 0


def cmd_protect(args: argparse.Namespace) -> int:
    root = git_root(args.repo)
    ensure_files(root)
    data = read_json(root / PROTECTED, {"version": 1, "areas": []})
    areas = data.setdefault("areas", [])
    pattern = args.pattern.replace("\\", "/").strip()
    for item in areas:
        if item.get("pattern") == pattern:
            item.update({"level": args.level, "reason": args.reason.strip(), "updated_at": now_iso()})
            write_json(root / PROTECTED, data)
            print(f"Updated protection: {pattern} ({args.level})")
            return 0
    areas.append(
        {
            "pattern": pattern,
            "level": args.level,
            "reason": args.reason.strip(),
            "added_at": now_iso(),
        }
    )
    write_json(root / PROTECTED, data)
    print(f"Protected: {pattern} ({args.level})")
    return 0


def cmd_unprotect(args: argparse.Namespace) -> int:
    root = git_root(args.repo)
    ensure_files(root)
    data = read_json(root / PROTECTED, {"version": 1, "areas": []})
    before = len(data.get("areas", []))
    data["areas"] = [a for a in data.get("areas", []) if a.get("pattern") != args.pattern]
    write_json(root / PROTECTED, data)
    print(f"Removed {before - len(data['areas'])} protection rule(s).")
    return 0


def cmd_list_protected(args: argparse.Namespace) -> int:
    root = git_root(args.repo)
    ensure_files(root)
    data = read_json(root / PROTECTED, {"version": 1, "areas": []})
    print(json.dumps(data, indent=2, sort_keys=True))
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--repo", help="Repository path (defaults to current Git root).")
    sub = p.add_subparsers(dest="command", required=True)

    s = sub.add_parser("init", help="Initialize .ai memory files.")
    s.set_defaults(func=cmd_init)

    s = sub.add_parser("add", help="Append a structured memory record.")
    s.add_argument("--kind", required=True, choices=[
        "invariant", "regression", "fix", "decision", "finding", "status", "correction", "failed-attempt"
    ])
    s.add_argument("--title", required=True)
    s.add_argument("--summary", required=True)
    s.add_argument("--tags", action="append", default=[])
    s.add_argument("--files", action="append", default=[])
    s.add_argument("--evidence")
    s.add_argument("--guard")
    s.add_argument("--validation")
    s.add_argument("--critical", action="store_true")
    s.set_defaults(func=cmd_add)

    s = sub.add_parser("search", help="Search memory records by keywords.")
    s.add_argument("query")
    s.add_argument("--limit", type=int, default=10)
    s.set_defaults(func=cmd_search)

    s = sub.add_parser("protect", help="Add or update a protected path glob.")
    s.add_argument("--pattern", required=True)
    s.add_argument("--reason", required=True)
    s.add_argument("--level", choices=["hard", "high-risk", "watch"], default="hard")
    s.set_defaults(func=cmd_protect)

    s = sub.add_parser("unprotect", help="Remove an exact protected pattern.")
    s.add_argument("--pattern", required=True)
    s.set_defaults(func=cmd_unprotect)

    s = sub.add_parser("list-protected", help="Print protected-area configuration.")
    s.set_defaults(func=cmd_list_protected)
    return p


def main() -> int:
    args = build_parser().parse_args()
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
